### ISSUE TITLE
Convite para Organização

### ISSUE THREAD

**Issue by caue-alves** [eduardohor/Ola-Mundo#1]
Olá @eduardohor, eu e meu amigo @Felipe-Souza-Pereira-Lima estamos desenvolvendo uma aplicação chamada [Dsa-Terminal](https://github.com/Dsa-Terminal) e estamos procurando desenvolvedores para o projeto. Vi que vc sabe php, o que ajudaria muito no nosso projeto, enfim, estamos convidando você para a organização, assim podemos amadurecer e aprender coisas novas com um projeto prático, onde todos vamos ganhar com uma equipe maior e com novos aprendizados. Caso vc aceite irei te enviar o convite das organizações @Dsa-Software e @Dsa-Terminal.

**Comment by eduardohor** [comment]
Olá @caue-alves! Gostei da proposta, ainda estou começando nesse universo mas topo qualquer desafio, estou muito dedicado! Como você disse, aprendendo e amadurecendo com projetos práticos. Aceito sim o convite!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
> Olá @caue-alves! Gostei da proposta, ainda estou começando nesse universo mas topo qualquer desafio, estou muito dedicado! Como você disse, aprendendo e amadurecendo com projetos práticos. Aceito sim o convite!  

Olá, também sou da organização com vi tarde amanha vou mandar o convite, Agradeço pela colaboração

**Comment by eduardohor** [comment]
Tá bem, aguardo!

**Comment by caue-alves** [comment]
Bom dia @eduardohor e já enviei o convite pelas duas organizações, o GitHub irá te mandar um e-mail notificando o convite onde você colocará no link que eles colocarem para vc e automaticamente o convite será aceito!

**Comment by eduardohor** [comment]
Recebi e já entreguei no link.

**Comment by caue-alves** [comment]
Ok, seja bem vindo! Por favor aceite o convite pela outra org, @Dsa-Terminal, assim poderemos trabalhar melhor

**Comment by Felipe-Souza-Pereira-Lima** [comment]
> Recebi e já entreguei no link.

Que bom que ja entrou, você tem hangousts do google, para o grupo da empresa?

**Comment by eduardohor** [comment]
Tenho sim

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Qual o seu mail

**Comment by eduardohor** [comment]
duduhenrry@gmail.com

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Obrigado vou mandar um convite

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Para o hangousts

**Comment by caue-alves** [comment]
vou fechar o issue, obrigado.
